### ISSUE TITLE
SteamAchievements

### ISSUE THREAD

**Issue by headshotczech** [00000vish/Steam-Two#1]
Hello, 

I am very interested about Steam achievements and hunting 
and little thinking if you can do "simple", "lightweight" program in C#, 
what can do this two things without crash game overlay: 

- Edit custum sound of Achievement notification popup (or default from choose ps4/xbox trophy sound) 
- Edit notification toast or do better notification (bigger, other design etc.) 

But mainly just option to enable future of Steam achievement sound. 

If this working and be great application, you can have more people of community, many people need this function long time. 

If you can do this i can send you some donate as thanks for your good work of course. 

Thank you for reply.

**Comment by 00000vish** [comment]
Sorry unlocking achievements are done with https://github.com/gibbed/SteamAchievementManager
